package com.TuDime.Prefrences;

public interface PrefrenceConstants {
    String PREFS_SERVER_URL = "prefs_server_url";
    String PREFS_USERNAME = "prefs_username";
    String PREFS_PROFILE_PIC = "prefs_profile_pic";
    String PREFS_USER_ID = "userId";
    String PREFS_DISCOVER_ME = "discoverMe";
    String PREFS_QB_USER_ID = "qbUserId";
    String PREFS_SESSION_TOKEN = "session";
    String PREFS_DEVICE_ID = "prefs_device_id";
    String PREFS_COUNTRY_NAME = "countryName";
    String PREFS_COUNTRY_CODE = "countryCode";
    String PREFS_PHONE_NUM = "phoneNumber";
    String PREFS_USERID = "PREFS_USERID";
    String PREFS_IS_NUMBER_VERIFIED = "prefs_is_number_verified";
    String PREFS_IS_PROFILE_REGISTERED = "prefs_is_profile_registered";
    String PREFS_WALLPAPER = "prefs_wallpaper";
    String PREFS_AVTAR_CODE = "prefs_avtar_code";
    String PREFS_CURRENT_STATUS = "prefs_current_status";
    String PREFS_ALL_STATUS = "prefs_all_status";
    String PREFS_APP_VERSION = "prefs_app_version";
    String PREFS_DEVICE_TOKEN = "prefs_device_token";
    String PREFS_KEYBOARD_HEIGHT = "prefs_keyboard_height";
    String PREFS_RANDOM_ID_FOR_CONTACT = "prefs_random_user_id";
    String PREFS_RINGTONE_TITLE = "prefs_ringtone_title";
    String PREFS_RINGTONE_URI = "prefs_ringtone_uri";
    String PREFS_RINGTONE_TITLE_GROUP = "prefs_ringtone_title_group";
    String PREFS_RINGTONE_URI_GROUP = "prefs_ringtone_uri_group";
    String PREFS_RINGTONE_TITLE_CALL = "prefs_ringtone_title_call";
    String PREFS_RINGTONE_URI_CALL = "prefs_ringtone_uri_call";
    String PREFS_VIBRATE = "prefs_vibrate";
    String PREFS_VIBRATE_GROUP = "prefs_vibrate_group";
    String PREFS_VIBRATE_CALL = "prefs_vibrate_call";
    String PREFS_IS_QB_USER_ID_UPDATED_ON_SERVER = "prefs_is_qb_user_id_updated_on_server";
    String PREFS_SHOW_MESSAGE_PREVIEW = "prefs_show_message_preview";
    String PREFS_AUTO_DOWNLOAD_MEDIA = "prefs_auto_download_media";
    String PREFS_IS_AGREEMENT_ACCEPTED = "prefs_is_agreement_accepted";
    String PREFS_TIMELINE_RESPONSE = "timeLineResponse";
    String PREFS_RADAR_DISTANCE = "radarDistance";
    String PREFS_PRIVACY_SELECTED_POSITION = "privacySelectedPostion";
    String PREFS_TIMELINE_SETTING_LIKES="timeline_likes";
    String PREFS_TIMELINE_SETTING_COMMENTS="timeline_comments";
    String PREFS_TIMELINE_SETTING_ALLOW_TAG="timeline_allow_tag";
    String CHAT_WINDOW_WALLPAPER = "chat_window_wallpaper";
}
